name: 'Branch Merger'
description: 'Keep your branches up to date.'
author: 'Patryk Tomczyk @patzick'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 500
runs:
  using: 'node12'
  main: 'dist/index.js'
