name: "Merger Action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        milliseconds: 1000
  
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: patzick/merger@master
      with:
        milliseconds: 666
