name: "Merger Action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run build
    - run: npm test
  
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: patzick/merger@master
      with:
        gitToken: ${{ secrets.GITHUB_TOKEN }}
        branches: |
          green*/*
          feat/**/*
          release/**/*
